### ISSUE TITLE
Some Cryptos (Terra, Avalanche ...) Do Not Work With NBitcoin 7.0.5

### ISSUE THREAD

**Issue by bo-vdx** [farukterzioglu/HDWallet#39]
The HDWallet project is referring to NBitcoin version 5 currently. 

When I'm referring NBitcoin version 7 together with HDWallet, I have error when generating HDWallet.Terra and HDWallet.Avalanche.

No implementation:
   at NBitcoin.IBitcoinSerializable.ReadWrite(BitcoinStream stream)
   at NBitcoin.BitcoinSerializableExtensions.ToBytes(IBitcoinSerializable serializable, Nullable`1 version)
   at HDWallet.Secp256.AccountSecpBase`1.GetWallet(UInt32 addressIndex, Boolean isInternal)
   at HDWallet.Secp256.AccountSecpBase`1.HDWallet.Core.IAccount<TWallet>.GetExternalWallet(UInt32 addressIndex)

Will there be future support for the NBitcoin 7+?

**Comment by farukterzioglu** [comment]
Thanks for reporting this, let me take a look. 
I can try to upgrade to latest NBitcoin version

**Comment by farukterzioglu** [comment]
Merged the fix, I will publish new Nuget versions soon.

**Comment by farukterzioglu** [comment]
I upgraded NBitcoin version (also added netstandart support)
You can use release candidate versions for now, they are stable I guess.
